# Site settings
title: Felipe Martins
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Felipe Martins - Desenvolvedor de Software
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://flpmartins88.github.io" # the base hostname & protocol for your site
twitter_username: flpmartins88
github_username:  flpmartins88

# Build settings
markdown: kramdown
